# Generated by Django 2.2.5 on 2022-05-30 21:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20220527_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='coversation', to=settings.AUTH_USER_MODEL),
        ),
    ]
